name: Automation-Delta-Children Workflow
on:
  schedule:
  - cron:  '30 0 * * *' #* The workflow every day at 00:30 UTC

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Usa 2 instancias paralelas
    steps:
      - name: Checkout code           
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: 'https://www.deltachildren.com/' # Espera a que esté disponible
          browser: chrome
          record: true
          parallel: true # Ejecuta las pruebas en paralelo usando la configuración anterior
      - name: Install dependencies
        run: npm install         
      - name: Run Cypress tests           
        run: npx cypress run  
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}









          















